<a href="https://colab.research.google.com/github/tahanaasir/Taha/blob/main/Session_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#access index value placed within square brackets
list_of_cars=['bmw', 'toyota', 'rolls royce', 'bently']
print(list_of_cars[2])

rolls royce


In [ ]:
list_of_cars=['bmw', 'toyota', 'rolls royce', 'bently']
list_of_cars.append('prado')
print(list_of_cars)

['bmw', 'toyota', 'rolls royce', 'bently', 'prado']


In [ ]:
list_of_cars=['bmw', 'toyota', 'rolls royce', 'bently']
list_of_cars.insert(2,'mercedes')
print(list_of_cars)

['bmw', 'toyota', 'mercedes', 'rolls royce', 'bently']


In [ ]:
list_of_cars=['bmw', 'toyota', 'rolls royce', 'bently']
list_of_cars.pop(1)
print(list_of_cars)

['bmw', 'rolls royce', 'bently']


In [ ]:
list_of_cars=['bmw', 'toyota', 'rolls royce', 'bently']
list_of_cars.pop()
print(list_of_cars)

['bmw', 'toyota', 'rolls royce']


In [ ]:
list_of_cars=['bmw', 'toyota', 'rolls royce', 'bently']
list_of_cars.remove('bmw')
print(list_of_cars)

['toyota', 'rolls royce', 'bently']


In [ ]:
list_of_cars=['bmw', 'toyota', 'rolls royce', 'bently']
del list_of_cars[1]
print(list_of_cars)

['bmw', 'rolls royce', 'bently']


In [ ]:
list_of_cars=['bmw', 'toyota', 'rolls royce', 'bently']
list_of_cars.clear()
print(list_of_cars)

[]


In [ ]:
list_of_cars=['bmw', 'toyota', 'rolls royce', 'bently']
list_of_cars.sort()
print(list_of_cars)

['bently', 'bmw', 'rolls royce', 'toyota']


In [ ]:
list_of_cars=['bmw', 'toyota', 'rolls royce', 'bently']
sorted(list_of_cars)
print(list_of_cars)

['bmw', 'toyota', 'rolls royce', 'bently']


In [ ]:
list_of_cars=['bmw', 'toyota', 'rolls royce', 'bently']
list_of_cars.reverse()
print(list_of_cars)

['bently', 'rolls royce', 'toyota', 'bmw']


In [ ]:
list_of_cars=['bmw', 'toyota', 'rolls royce', 'bently']
len(list_of_cars)
print(list_of_cars)

['bmw', 'toyota', 'rolls royce', 'bently']


Program 3: Write a program to create and print Zero, one, Two and multi dimensional array importing NumPy module as array function.

In [ ]:
import numpy as np
arr=np.array(50)
print('Zero dimensional array: ',arr)

arr1=np.array([10,20,30,40,50])
print('One dimensional array: ',arr1)

arr2=np.array([[2,4,16],[3,9,81]])
print('Two dimensional array:\n',arr2)

arr3=np.array([[[1,1,1,1],[2,2,2,2,],[3,3,3,3],[4,4,4,4]]])
print('Multi dimensional array:\n',arr3)

Zero dimensional array:  50
One dimensional array:  [10 20 30 40 50]
Two dimensional array:
 [[ 2  4 16]
 [ 3  9 81]]
Multi dimensional array:
 [[[1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]
  [4 4 4 4]]]


In [ ]:
!pip3 install ColabTurtle
from ColabTurtle.Turtle import*
initializeTurtle()

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip3 install ColabTurtle
from ColabTurtle.Turtle import *

import ColabTurtle.Turtle as t 
initializeTurtle()

t.right(90)
t.forward(100)
t.left(90)
t.backward(100)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip3 install ColabTurtle
from ColabTurtle.Turtle import *

import ColabTurtle.Turtle as t 
initializeTurtle()

t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import ColabTurtle.Turtle as t
initializeTurtle()
side_length = 100
angle = 360/4

for i in range(4):
  forward(side_length)
  right(angle)

In [ ]:
import ColabTurtle.Turtle as t
initializeTurtle()
side_length = 100
angle = 890/4

for i in range(4):
  forward(side_length)
  right(angle)

In [ ]:
import ColabTurtle.Turtle as t
initializeTurtle()

t.color('orange')
t.forward(100)
t.left(90)

t.color('purple')
t.forward(100)
t.left(90)

t.color('pink')
t.forward(100)
t.left(90)

t.color('Green')
t.forward(100)
t.left(90)

In [ ]:
!pip3 install ColabTurtle
from ColabTurtle.Turtle import *

import ColabTurtle.Turtle as t 
initializeTurtle()

t.forward(140)
t.left(90)
t.forward(70)
t.left(90)
t.forward(140)
t.left(90)
t.forward(70)
t.left(90)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip3 install ColabTurtle
from ColabTurtle.Turtle import *

import ColabTurtle.Turtle as t 
initializeTurtle()

t.forward(100)
t.left(120)
t.forward(100)
t.left(120)
t.forward(100)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
