<a href="https://colab.research.google.com/github/tahanaasir/Taha/blob/main/Session_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a program to create a function which returns square root of a number. Call the function to print square root of consecutive 10 numbers.

In [ ]:
#define function
def square_root(num):
  return num*num

for i in range(1,11):
#calling function
  result = square_root(i)
  print('Square of', i, '=', result)  

Square of 1 = 1
Square of 2 = 4
Square of 3 = 9
Square of 4 = 16
Square of 5 = 25
Square of 6 = 36
Square of 7 = 49
Square of 8 = 64
Square of 9 = 81
Square of 10 = 100


What are the uses of following functions :
lstrip
rstrip
strip
Write codes to use the above functions.

In [ ]:
# use of lstrip() method returns a copy of the string with leading characters removed (based on the string argument passed).

word_1= '             Taha Nasir'
new_word_1= word_1.lstrip()
print(word_1)
print(new_word_1)

# use of rstrip() method removes any trailing characters (characters at the end a string), space is the default trailing character to remove.

word_2= 'Taha                  Nasir'
new_word_2= word_2.rstrip()
print(word_2)
print(new_word_2)

# use of strip() method removes any leading (spaces at the beginning) and trailing (spaces at the end) characters (space is the default leading character to remove).

word_3= '              Happy New Year'
new_word_3= word_3.strip()
print(word_3)
print(new_word_3)

             Taha Nasir
Taha Nasir
Taha                  Nasir
Taha                  Nasir
              Happy New Year
Happy New Year


If-else
Write a Python program to check whether an alphabet is a vowel or consonant

In [ ]:
alphabet = input('Enter the alphabet: ')

if alphabet in ('a', 'e', 'i', 'o', 'u'):
  print(alphabet,' is a vowel.')

else:
  print(alphabet,' is a constant.')  

Enter the alphabet: e
e  is a vowel.


If-elif-else
Take two numbers from the user, compare and print the smaller number. Also consider a condition where both the numbers can be same.

In [ ]:
number1=int(input("First number."))
number2=int(input('Second number.'))
if number1 > number2:
   print('The first number is greater than second number')

elif number1 < number2:
  print('The first number is less than second number.')

else:
  print('The numbers are equal.')     

First number.4
Second number.7
The first number is less than second number.


List type data+ for loop
Write a program to print the all the elements in a list data type using for loop.

In [ ]:
list_of_cars = ['Rolls Royce', 'Mercedes', 'Bently', 'Nissan', 'Toyota', 'GMC']

# access items of a list while using for loop
for car in list_of_cars:
    print(car)

Rolls Royce
Mercedes
Bently
Nissan
Toyota
GMC


Dictionary type
Create a dictionary data-type of a student with name, id and course. Write a program to print all the key-value pair in the dictionary. Add another key-value pair called gender to update the dictionary and print the updated dictionary.

In [ ]:
student = {'Name': 'Taha Nasir', 'ID': '2022-519' , 'Course': 'BSC CC'}
print('Display key-value pairs')
for key,value in student.items():
  print(f'\nKey: {key}')
  print(f'\nValue: {value}')

student['gender'] = 'Male'
print(student)

Display key-value pairs

Key: Name

Value: Taha Nasir

Key: ID

Value: 2022-519

Key: Course

Value: BSC CC
{'Name': 'Taha Nasir', 'ID': '2022-519', 'Course': 'BSC CC', 'gender': 'Male'}


Refer Session 10
Tuple data type
Declare 2 Tuples comprising of 4 leap years and 4 non leap years
i.	Print tuples
ii.	Concatenate 2 tuples
iii.	Multiple each tuple 3 times
iv.	Compare 2 tuples
v.	Find the length of tuples
vi.	Find the sum of elements in each of the tuples
vii.	Sort the elements in each of the tuples
viii.	Swap the tuples

In [ ]:
#integer tuples comprising of leap years and non leap years seprately
leap_years = (2000,2004,2008,2012)
non_leap_years = (2023,2025,2026,2027)
print('List of 4 leap years:', leap_years[0:5])
print('List of 4 non leap years:', non_leap_years[0:5])

#concatenate 2 tuples
print('The list of few leap years and non leap years are:\n ', leap_years+non_leap_years)

#multiplying each tuples 3 times by using * operator
print(leap_years*3)

#comparing 2 tuples
print(leap_years==non_leap_years)

#finding the lenght of tuples
print(len(leap_years))
print(len(non_leap_years))

#finding the sum of elements in each of the tuples
print(sum(leap_years))
print(sum(non_leap_years))

#sorting the elements in each of tuples
print(sorted(leap_years))
print(sorted(non_leap_years))

#swapping two tuples
leap_years,non_leap_years=non_leap_years,leap_years
print('4 non leap years:', leap_years)
print('4 leap years:', non_leap_years)

List of 4 leap years: (2000, 2004, 2008, 2012)
List of 4 non leap years: (2023, 2025, 2026, 2027)
The list of few leap years and non leap years are:
  (2000, 2004, 2008, 2012, 2023, 2025, 2026, 2027)
(2000, 2004, 2008, 2012, 2000, 2004, 2008, 2012, 2000, 2004, 2008, 2012)
False
4
4
8024
8101
[2000, 2004, 2008, 2012]
[2023, 2025, 2026, 2027]
4 non leap years: (2023, 2025, 2026, 2027)
4 leap years: (2000, 2004, 2008, 2012)


Nested for loop
Write a program to print the following number pattern.

In [ ]:
#printing odd numbers pyramid by using while loop

n=int(input('Enter the number of rows: '))
i=1
while i<=n:
  j=1
  while j<=i:
    print((i*2-1),end=' ')
    j=j+1
  i=i+1
  print() 

Enter the number of rows: 9
1 
3 3 
5 5 5 
7 7 7 7 
9 9 9 9 9 
11 11 11 11 11 11 
13 13 13 13 13 13 13 
15 15 15 15 15 15 15 15 
17 17 17 17 17 17 17 17 17 


String + for loop
Write a  program to Count the Number of Occurrence of a Character in String.

In [ ]:
#counting the number of occurence of a character in string

count = 0
my_string = 'Possessionlessnesses'
my_char = 's'
for i in my_string:
  if i == my_char:
    count+=1
print(count)

9


Array
Write a program to create and print Zero, one, Two and multi dimensional array importing NumPy module as array function.

In [ ]:
import numpy as np
#zero dimensional array
arr=np.array(30)
print('Zero dimensional array: ',arr)
#one dimensional array
arr1=np.array([1,2,3,4,5])
print('One dimensional array: ',arr1)
#two dimensional array
arr2=np.array([[2,4,16],[3,9,81]])
print('Two dimensional array:\n',arr2)
#multi dimensional array
arr3=np.array([[[5,5,5,5],[6,6,6,6],[7,7,7,7],[8,8,8,8]]])
print('Multi dimensional array:\n',arr3)

Zero dimensional array:  30
One dimensional array:  [1 2 3 4 5]
Two dimensional array:
 [[ 2  4 16]
 [ 3  9 81]]
Multi dimensional array:
 [[[5 5 5 5]
  [6 6 6 6]
  [7 7 7 7]
  [8 8 8 8]]]


Write a program to draw a draw square in Python Turtle with different color sides.

In [ ]:
import ColabTurtle.Turtle as t
initializeTurtle()
#drawing 1st side
t.color('orange')
t.forward(100)        #Forwarded turtle by 100 units
t.left(90)            #Turned turtle by 90 degree

#drawing 2nd side
t.color('purple')
t.forward(100)        #Forwarded turtle by 100 units  
t.left(90)            #Turned turtle by 90 degree

#drawing 3rd side
t.color('pink')
t.forward(100)        #Forwarded turtle by 100 units
t.left(90)            #Turned turtle by 90 degree

#drawing 4th side
t.color('Green')
t.forward(100)        #Forwarded turtle by 100 units
t.left(90)            #Turned turtle by 90 degrees

Array + nested for loop
Write a program to Sort Array in Descending Order.

In [ ]:
import numpy as np 
arr=np.array([45, 52, 16, 22, 37, 88, 64, 78])
temp=0;
print("Elements of original array: ");    
for i in range(0, len(arr)):     
    print(arr[i]), 
for i in range(0, len(arr)):    
    for j in range(i+1, len(arr)):    
        if(arr[i] < arr[j]):    
            temp = arr[i];    
            arr[i] = arr[j];    
            arr[j] = temp;    
     
print();  
print("Elements of array sorted in descending order: ");    
for i in range(0, len(arr)):     
    print(arr[i]),

Elements of original array: 
45
52
16
22
37
88
64
78

Elements of array sorted in descending order: 
88
78
64
52
45
37
22
16
